### ISSUE TITLE
Feature request: Give the option to extract section with a regex

### ISSUE THREAD

**Issue by ebetica** [bbawj/obsidian-semantic-search#1]
I would like to extract sections out with a custom logic. It would be great if we can use a custom regex instead of headers.

Another random comment: it seems that notes without any headers are treated as non-existent. I keep a lot of notes without header organization, and would still like to search through it.

**Comment by bbawj** [comment]
Hi @ebetica thanks for the feedback! This seems like a good way to generalize the functionality. I will work on this and release it as version 0.2.

**Comment by beingskyler** [comment]
Came here with the same question. Many of my files do not use headings.

**Comment by bbawj** [comment]
Please try out release 0.2.0 for this feature!
