### ISSUE TITLE
Does not generate anything in certain cases

### ISSUE THREAD

**Issue by rizerphe** [bbawj/obsidian-semantic-search#3]
I tested this on as minimal of a setup as I could:

![image](https://user-images.githubusercontent.com/44440399/237034926-e67cda05-e5ef-443f-a303-66335be3e730.png)

Steps to reproduce:
- Create a new empty vault
- Install the plugin, do not change the settings other than your API key
- Create a file with a single h1 heading and nothing else
- Run `Generate input`

The `input.csv` file is generated with the file size of 0 bytes. The same happens if it's a h2 heading or if it's just the file content; noting changes if there's something after the h1 heading - the only case in which it works is if it's strictly a h2 heading and then some content. Changing the heading type to `h1` in the settings does solve the issue, but requires a reload.

Expected behavior: with the splitter set to h2, a note like this:
```md
# content
content
```
Should generate at least some embeddings. Any higher order heading should act as a section splitter, and a note without a heading at all should be considered a section.

**Comment by bbawj** [comment]
Hey there thanks for pointing this out. The current logic for section splitting is not intuitive. #1 will solve this by giving the user more fine grained control over how sections are created.

**Comment by rizerphe** [comment]
Can we expect some intuitive regex presets? That would be immensely useful

**Comment by bbawj** [comment]
The README contains an example of how you would match all types of headings as the start of a new section. Are you referring to adding more examples?

**Comment by rizerphe** [comment]
No, while an example in the README is certainly useful, it's not what I'm referring to. It would be very useful if I didn't have to open the README to understand how to use your plugin effectively. I suggest having a few presets you expect to be the most common available right there in the settings, through a simple dropdown etc. This makes it very easy for most - it's just a two click process - but still gives us the full flexibility of a regex.

**Comment by bbawj** [comment]
I see your point, thanks for the feedback! I am not too sure which presets will be useful, but for now I think adding those to match different headings should suffice.
