### ISSUE TITLE
Caching unchanged embeddings

### ISSUE THREAD

**Issue by abimek** [bbawj/obsidian-semantic-search#5]
Is there an option to not reload all embeddings during a create embeddings. I was thinking that we generate a new input.csv and compare that to the old, find the newly changed and create embeddings only for those and replace them in the embedding.csv. Will save money as well

**Comment by bbawj** [comment]
Currently there is no option to do so, but that is a good idea. 

However, I am not too sure of an efficient way to do this. It seems like it will take a lot of string comparison operations, especially as the csv files become larger. I may come back to this if it becomes a highly desired feature.

**Comment by bbawj** [comment]
> This is a highly desired feature.
> 
> It seems that the file date of modification could be a key except if old files are added. In which case we could have a specific command to include them.

I dont know why I never thought of using modified time before. Let me try to implement this

**Comment by bbawj** [comment]
completed with release [0.3.0](https://github.com/bbawj/obsidian-semantic-search/releases/tag/0.3.0)
