### ISSUE TITLE
'embedding.csv'  "name,mtime,header,embedding" replicated line

### ISSUE THREAD

**Issue by hpchavaz** [bbawj/obsidian-semantic-search#9]
As I wrote préviously
> By the way in 'embedding.csv' file the line "name,mtime,header,embedding" is replicated probably for each batch.

After I cured the 'embedding.csv' file by removing these lines,
I finally got the plugin to work, It answers to prompts and make ling recommendations from the current selection.

_Originally posted by @hpchavaz in https://github.com/bbawj/obsidian-semantic-search/issues/2#issuecomment-1660292594_

**Comment by bbawj** [comment]
thanks for raising this @hpchavaz  this has been fixed with release 0.3.3
